// Command seed writes deterministic JSON fixtures to
// testdata/fixtures and prints a SHA-256 of the generated bytes.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/soma-genesis/scenario-2-pricing-perf/internal/domain"
	"github.com/soma-genesis/scenario-2-pricing-perf/internal/seeddata"
	"github.com/soma-genesis/scenario-2-pricing-perf/internal/security"
	"github.com/soma-genesis/scenario-2-pricing-perf/internal/storage"
)

func main() {
	out := flag.String("out", "testdata/fixtures", "output directory for fixtures")
	profile := flag.String("profile", "medium", "profile: small | medium | large")
	flag.Parse()

	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}

	profiles := map[string]seeddata.Profile{
		"small":  seeddata.Small,
		"medium": seeddata.Medium,
		"large":  seeddata.Large,
	}
	p, ok := profiles[*profile]
	if !ok {
		log.Fatalf("unknown profile: %s", *profile)
	}
	ds := seeddata.Build(int64(seeddata.DefaultSeed), p)
	path := filepath.Join(*out, *profile+".json")
	if err := ds.Save(path); err != nil {
		log.Fatal(err)
	}
	hash := security.SHA256FileMust(path)
	fmt.Printf("wrote %s sha256=%s profile=%s tenants=%d products=%d customers=%d promotions=%d conditions=%d\n",
		path, hash, p.Name, len(ds.TenantIDs), len(ds.Products), len(ds.Customers), len(ds.Promotions), len(ds.Conditions))

	// Always also write small.json and large.json if not present.
	if *profile == "medium" {
		dsSmall := seeddata.Build(int64(seeddata.DefaultSeed), seeddata.Small)
		_ = dsSmall.Save(filepath.Join(*out, "small.json"))
		dsLarge := seeddata.Build(int64(seeddata.DefaultSeed), seeddata.Large)
		_ = dsLarge.Save(filepath.Join(*out, "large.json"))
		hs := security.SHA256FileMust(filepath.Join(*out, "small.json"))
		hl := security.SHA256FileMust(filepath.Join(*out, "large.json"))
		fmt.Printf("wrote %s sha256=%s\n", filepath.Join(*out, "small.json"), hs)
		fmt.Printf("wrote %s sha256=%s\n", filepath.Join(*out, "large.json"), hl)
	}

	// Populate the in-memory store to confirm seed values load.
	mem := storage.NewMemoryStore()
	for _, t := range ds.TenantIDs {
		mem.PutTenant(domain.Tenant{ID: t, Name: t})
	}
	for _, p := range ds.Products {
		mem.PutProduct(p)
	}
	for _, c := range ds.Customers {
		mem.PutCustomer(c)
	}
	condsByPromo := map[string][]domain.PromotionCondition{}
	for _, c := range ds.Conditions {
		condsByPromo[c.PromotionID] = append(condsByPromo[c.PromotionID], c)
	}
	for _, p := range ds.Promotions {
		mem.PutPromotion(p, condsByPromo[p.ID])
	}
	fmt.Printf("in-memory store populated with %d products and %d promotions\n", len(ds.Products), len(ds.Promotions))
}
